version: 2.1
executors:
  windows-executor:
    docker:
      - image: python:3.8
jobs:
  build:
    executor: windows-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Unit Tests
          command: python C:\Users\Nerma\CalculatorLibrary\calculator.py
      - run:
          name: Run Integration Tests
          command: python C:\Users\Nerma\CalculatorLibrary\test\test_calculator.py
